<?php if(!defined("RUN_MODE")) die();?>
<?php if($extView = $this->getExtViewFile(__FILE__)){include $extView; return helper::cd();}?>
<?php
/* Import js for jquery. */
js::import($jsRoot  . 'jquery/chosen/chosenicons.min.js');
css::import($jsRoot . 'jquery/chosen/chosenicons.min.css');
?>
<script>
$(function()
{
    $('.chosen-icons').chosenIcons();
});
</script>
<style>
@font-face{font-family:ZenIcon; font-style:normal; font-weight:400; src:url(<?php echo $webRoot;?>zui/fonts/zenicon.eot?v=2.2.0); src:url(<?php echo $webRoot;?>zui/fonts/zenicon.eot?#iefix&v=2.2.0) format('embedded-opentype'),url(<?php echo $webRoot;?>zui/fonts/zenicon.woff?v=2.2.0) format('woff'),url(<?php echo $webRoot;?>zui/fonts/zenicon.ttf?v=2.2.0) format('truetype'),url(<?php echo $webRoot;?>zui/fonts/zenicon.svg#regular?v=2.2.0) format('svg')}
.chosen-icons .icon, .chosen-icons [class*=" icon-"], .chosen-icons [class^=icon-] {font-family: ZenIcon;}
.chosen-container .chosen-results {max-height: 200px}
.chosen-icons .icon-resize:before{content:'\e667'}
.chosen-icons .icon-expand-full:before{content:'\e6a3'}
.chosen-icons .icon-arrows-alt:before{content:'\e6a3'}
.chosen-icons .icon-fullscreen:before{content:'\e6a3'}
.chosen-icons .icon-collapse-full:before{content:'\e682'}
.chosen-icons .icon-yinyang:before{content:'\e687'}
.chosen-icons .icon-taiji:before{content:'\e687'}
.chosen-icons .icon-window:before{content:'\e68e'}
.chosen-icons .icon-window-alt:before{content:'\e68f'}
.chosen-icons .icon-carousel:before{content:'\e6b0'}
.chosen-icons .icon-spinner-snake:before{content:'\e97b'}
.chosen-icons .icon-spinner-indicator:before{content:'\e97c'}
.chosen-icons .icon-check-board:before{content:'\e9b8'}
.chosen-icons .icon-bar-chart:before{content:'\f080'}
.chosen-icons .icon-bar-chart-o:before{content:'\f080'}
.chosen-icons .icon-github:before{content:'\f09b'}
.chosen-icons .icon-dot-circle:before{content:'\f192'}
.chosen-icons .icon-dot-circle-o:before{content:'\f192'}
.chosen-icons .icon-cube-alt:before{content:'\f1b2'}
.chosen-icons .icon-cubes:before{content:'\f1b3'}
.chosen-icons .icon-file-pdf:before{content:'\f1c1'}
.chosen-icons .icon-file-word:before{content:'\f1c2'}
.chosen-icons .icon-file-excel:before{content:'\f1c3'}
.chosen-icons .icon-file-powerpoint:before{content:'\f1c4'}
.chosen-icons .icon-file-image:before{content:'\f1c5'}
.chosen-icons .icon-file-photo:before{content:'\f1c5'}
.chosen-icons .icon-file-picture:before{content:'\f1c5'}
.chosen-icons .icon-file-archive:before{content:'\f1c6'}
.chosen-icons .icon-file-zip:before{content:'\f1c6'}
.chosen-icons .icon-file-audio:before{content:'\f1c7'}
.chosen-icons .icon-file-sound:before{content:'\f1c7'}
.chosen-icons .icon-file-movie:before{content:'\f1c8'}
.chosen-icons .icon-file-video:before{content:'\f1c8'}
.chosen-icons .icon-file-code:before{content:'\f1c9'}
.chosen-icons .icon-circle-o-notch:before{content:'\f1ce'}
.chosen-icons .icon-chanzhi:before{content:'\e906'}
.chosen-icons .icon-chanzhi-pro:before{content:'\e905'}
.chosen-icons .icon-zsite:before{content:'\e904'}
.chosen-icons .icon-zsite-pro:before{content:'\e903'}
.chosen-icons .icon-qq:before{content:'\f600'}
.chosen-icons .icon-wechat:before{content:'\f1d7'}
.chosen-icons .icon-weixin:before{content:'\f1d7'}
.chosen-icons .icon-history:before{content:'\f1da'}
.chosen-icons .icon-circle-thin:before{content:'\f1db'}
.chosen-icons .icon-sliders:before{content:'\f1de'}
.chosen-icons .icon-newspaper-o:before{content:'\f1ea'}
.chosen-icons .icon-calculator:before{content:'\f1ec'}
.chosen-icons .icon-paint-brush:before{content:'\f1fc'}
.chosen-icons .icon-area-chart:before{content:'\f1fe'}
.chosen-icons .icon-pie-chart:before{content:'\f200'}
.chosen-icons .icon-line-chart:before{content:'\f201'}
.chosen-icons .icon-toggle-off:before{content:'\f204'}
.chosen-icons .icon-toggle-on:before{content:'\f205'}
.chosen-icons .icon-diamond:before{content:'\f219'}
.chosen-icons .icon-venus:before{content:'\f221'}
.chosen-icons .icon-mars:before{content:'\f222'}
.chosen-icons .icon-server:before{content:'\f233'}
.chosen-icons .icon-music:before{content:'\e602'}
.chosen-icons .icon-search:before{content:'\e603'}
.chosen-icons .icon-envelope:before{content:'\e604'}
.chosen-icons .icon-heart:before{content:'\e605'}
.chosen-icons .icon-star:before{content:'\e606'}
.chosen-icons .icon-star-empty:before{content:'\e607'}
.chosen-icons .icon-user:before{content:'\e608'}
.chosen-icons .icon-film:before{content:'\e609'}
.chosen-icons .icon-th-large:before{content:'\e60a'}
.chosen-icons .icon-th:before{content:'\e60b'}
.chosen-icons .icon-th-list:before{content:'\e60c'}
.chosen-icons .icon-ok:before{content:'\e60d'}
.chosen-icons .icon-check:before{content:'\e60d'}
.chosen-icons .icon-remove:before{content:'\d7'}
.chosen-icons .icon-times:before{content:'\d7'}
.chosen-icons .icon-zoom-in:before{content:'\e60f'}
.chosen-icons .icon-zoom-out:before{content:'\e610'}
.chosen-icons .icon-off:before{content:'\e611'}
.chosen-icons .icon-cog:before{content:'\e613'}
.chosen-icons .icon-trash:before{content:'\e614'}
.chosen-icons .icon-home:before{content:'\e615'}
.chosen-icons .icon-file-o:before{content:'\e616'}
.chosen-icons .icon-file-alt:before{content:'\e616'}
.chosen-icons .icon-time:before{content:'\e617'}
.chosen-icons .icon-download-alt:before{content:'\e618'}
.chosen-icons .icon-download:before{content:'\e619'}
.chosen-icons .icon-upload:before{content:'\e61a'}
.chosen-icons .icon-inbox:before{content:'\e61b'}
.chosen-icons .icon-play-circle:before{content:'\e61c'}
.chosen-icons .icon-repeat:before{content:'\e61d'}
.chosen-icons .icon-refresh:before{content:'\e61e'}
.chosen-icons .icon-list-alt:before{content:'\e61f'}
.chosen-icons .icon-lock:before{content:'\e620'}
.chosen-icons .icon-flag:before{content:'\e621'}
.chosen-icons .icon-headphones:before{content:'\e622'}
.chosen-icons .icon-volume-off:before{content:'\e623'}
.chosen-icons .icon-volume-up:before{content:'\e625'}
.chosen-icons .icon-qrcode:before{content:'\e626'}
.chosen-icons .icon-barcode:before{content:'\e627'}
.chosen-icons .icon-tag:before{content:'\e628'}
.chosen-icons .icon-tags:before{content:'\e629'}
.chosen-icons .icon-book:before{content:'\e62a'}
.chosen-icons .icon-bookmark:before{content:'\e62b'}
.chosen-icons .icon-print:before{content:'\e62c'}
.chosen-icons .icon-camera:before{content:'\e62d'}
.chosen-icons .icon-font:before{content:'\e62e'}
.chosen-icons .icon-bold:before{content:'\e62f'}
.chosen-icons .icon-italic:before{content:'\f033'}
.chosen-icons .icon-header:before{content:'\f1dc'}
.chosen-icons .icon-underline:before{content:'\f0cd'}
.chosen-icons .icon-strikethrough:before{content:'\f0cc'}
.chosen-icons .icon-eraser:before{content:'\f12d'}
.chosen-icons .icon-align-justify:before{content:'\e636'}
.chosen-icons .icon-list:before{content:'\e637'}
.chosen-icons .icon-picture:before{content:'\e63b'}
.chosen-icons .icon-pencil:before{content:'\e63c'}
.chosen-icons .icon-map-marker:before{content:'\e63d'}
.chosen-icons .icon-adjust:before{content:'\e63e'}
.chosen-icons .icon-tint:before{content:'\e63f'}
.chosen-icons .icon-edit:before{content:'\e640'}
.chosen-icons .icon-share:before{content:'\e641'}
.chosen-icons .icon-checked:before{content:'\e642'}
.chosen-icons .icon-move:before{content:'\e643'}
.chosen-icons .icon-arrows:before{content:'\e643'}
.chosen-icons .icon-step-backward:before{content:'\e644'}
.chosen-icons .icon-fast-backward:before{content:'\e645'}
.chosen-icons .icon-backward:before{content:'\e646'}
.chosen-icons .icon-play:before{content:'\e647'}
.chosen-icons .icon-pause:before{content:'\e648'}
.chosen-icons .icon-stop:before{content:'\e649'}
.chosen-icons .icon-forward:before{content:'\e64a'}
.chosen-icons .icon-fast-forward:before{content:'\e64b'}
.chosen-icons .icon-step-forward:before{content:'\e64c'}
.chosen-icons .icon-eject:before{content:'\e64d'}
.chosen-icons .icon-chevron-left:before{content:'\e64e'}
.chosen-icons .icon-chevron-right:before{content:'\e64f'}
.chosen-icons .icon-plus-sign:before{content:'\e650'}
.chosen-icons .icon-minus-sign:before{content:'\e651'}
.chosen-icons .icon-remove-sign:before{content:'\e652'}
.chosen-icons .icon-ok-sign:before{content:'\e653'}
.chosen-icons .icon-check-circle:before{content:'\e653'}
.chosen-icons .icon-question-sign:before{content:'\e654'}
.chosen-icons .icon-info-sign:before{content:'\e655'}
.chosen-icons .icon-remove-circle:before{content:'\e657'}
.chosen-icons .icon-ok-circle:before{content:'\e658'}
.chosen-icons .icon-check-circle-o:before{content:'\e658'}
.chosen-icons .icon-ban-circle:before{content:'\e659'}
.chosen-icons .icon-arrow-left:before{content:'\e65a'}
.chosen-icons .icon-arrow-right:before{content:'\e65b'}
.chosen-icons .icon-arrow-up:before{content:'\e65c'}
.chosen-icons .icon-arrow-down:before{content:'\e65d'}
.chosen-icons .icon-share-alt:before{content:'\e65e'}
.chosen-icons .icon-resize-full:before{content:'\e65f'}
.chosen-icons .icon-resize-small:before{content:'\e660'}
.chosen-icons .icon-plus:before{content:'\e661'}
.chosen-icons .icon-minus:before{content:'\e662'}
.chosen-icons .icon-asterisk:before{content:'\e663'}
.chosen-icons .icon-exclamation-sign:before{content:'\e664'}
.chosen-icons .icon-gift:before{content:'\e665'}
.chosen-icons .icon-leaf:before{content:'\e666'}
.chosen-icons .icon-eye-open:before{content:'\e668'}
.chosen-icons .icon-eye-close:before{content:'\e669'}
.chosen-icons .icon-warning-sign:before{content:'\e66a'}
.chosen-icons .icon-plane:before{content:'\e66b'}
.chosen-icons .icon-calendar:before{content:'\e66c'}
.chosen-icons .icon-random:before{content:'\e66d'}
.chosen-icons .icon-comment:before{content:'\e66e'}
.chosen-icons .icon-chevron-up:before{content:'\e670'}
.chosen-icons .icon-chevron-down:before{content:'\e671'}
.chosen-icons .icon-shopping-cart:before{content:'\e673'}
.chosen-icons .icon-folder-close:before{content:'\e674'}
.chosen-icons .icon-folder-open:before{content:'\e675'}
.chosen-icons .icon-resize-v:before{content:'\e676'}
.chosen-icons .icon-resize-h:before{content:'\e677'}
.chosen-icons .icon-bar-chart-alt:before{content:'\e678'}
.chosen-icons .icon-camera-retro:before{content:'\e679'}
.chosen-icons .icon-key:before{content:'\e67a'}
.chosen-icons .icon-cogs:before{content:'\e67b'}
.chosen-icons .icon-comments:before{content:'\e67c'}
.chosen-icons .icon-thumbs-o-up:before{content:'\e67d'}
.chosen-icons .icon-thumbs-o-down:before{content:'\e67e'}
.chosen-icons .icon-star-half:before{content:'\e67f'}
.chosen-icons .icon-heart-empty:before{content:'\e680'}
.chosen-icons .icon-signout:before{content:'\e681'}
.chosen-icons .icon-pushpin:before{content:'\e683'}
.chosen-icons .icon-external-link:before{content:'\e684'}
.chosen-icons .icon-signin:before{content:'\e685'}
.chosen-icons .icon-trophy:before{content:'\e686'}
.chosen-icons .icon-upload-alt:before{content:'\e688'}
.chosen-icons .icon-lemon:before{content:'\e689'}
.chosen-icons .icon-phone:before{content:'\e68a'}
.chosen-icons .icon-check-empty:before{content:'\e68b'}
.chosen-icons .icon-bookmark-empty:before{content:'\e68c'}
.chosen-icons .icon-phone-sign:before{content:'\e68d'}
.chosen-icons .icon-credit:before{content:'\e690'}
.chosen-icons .icon-rss:before{content:'\e691'}
.chosen-icons .icon-hdd:before{content:'\e692'}
.chosen-icons .icon-bullhorn:before{content:'\e693'}
.chosen-icons .icon-bell:before{content:'\e694'}
.chosen-icons .icon-certificate:before{content:'\e695'}
.chosen-icons .icon-hand-right:before{content:'\e696'}
.chosen-icons .icon-hand-left:before{content:'\e697'}
.chosen-icons .icon-hand-up:before{content:'\e698'}
.chosen-icons .icon-hand-down:before{content:'\e699'}
.chosen-icons .icon-circle-arrow-left:before{content:'\e69a'}
.chosen-icons .icon-circle-arrow-right:before{content:'\e69b'}
.chosen-icons .icon-circle-arrow-up:before{content:'\e69c'}
.chosen-icons .icon-circle-arrow-down:before{content:'\e69d'}
.chosen-icons .icon-globe:before{content:'\e69e'}
.chosen-icons .icon-wrench:before{content:'\e69f'}
.chosen-icons .icon-tasks:before{content:'\e6a0'}
.chosen-icons .icon-filter:before{content:'\e6a1'}
.chosen-icons .icon-group:before{content:'\e6a4'}
.chosen-icons .icon-link:before{content:'\e6a5'}
.chosen-icons .icon-cloud:before{content:'\e6a6'}
.chosen-icons .icon-beaker:before{content:'\e6a7'}
.chosen-icons .icon-cut:before{content:'\e6a8'}
.chosen-icons .icon-copy:before{content:'\e6a9'}
.chosen-icons .icon-paper-clip:before{content:'\e6aa'}
.chosen-icons .icon-save:before{content:'\e6ab'}
.chosen-icons .icon-sign-blank:before{content:'\e6ac'}
.chosen-icons .icon-bars:before{content:'\e6ad'}
.chosen-icons .icon-reorder:before{content:'\e6ad'}
.chosen-icons .icon-list-ul:before{content:'\e6ae'}
.chosen-icons .icon-list-ol:before{content:'\e6af'}
.chosen-icons .icon-table:before{content:'\e6b2'}
.chosen-icons .icon-magic:before{content:'\e6b3'}
.chosen-icons .icon-caret-down:before{content:'\e6b8'}
.chosen-icons .icon-caret-up:before{content:'\e6b9'}
.chosen-icons .icon-caret-left:before{content:'\e6ba'}
.chosen-icons .icon-caret-right:before{content:'\e6bb'}
.chosen-icons .icon-columns:before{content:'\e6bc'}
.chosen-icons .icon-sort:before{content:'\e6bd'}
.chosen-icons .icon-sort-down:before{content:'\e6be'}
.chosen-icons .icon-sort-up:before{content:'\e6bf'}
.chosen-icons .icon-envelope-alt:before{content:'\e6c0'}
.chosen-icons .icon-undo:before{content:'\e6c1'}
.chosen-icons .icon-dashboard:before{content:'\e6c3'}
.chosen-icons .icon-comment-alt:before{content:'\e6c4'}
.chosen-icons .icon-comments-alt:before{content:'\e6c5'}
.chosen-icons .icon-bolt:before{content:'\e6c6'}
.chosen-icons .icon-sitemap:before{content:'\e6c7'}
.chosen-icons .icon-umbrella:before{content:'\e6c8'}
.chosen-icons .icon-paste:before{content:'\e6c9'}
.chosen-icons .icon-lightbulb:before{content:'\e6ca'}
.chosen-icons .icon-exchange:before{content:'\e6cb'}
.chosen-icons .icon-cloud-download:before{content:'\e6cc'}
.chosen-icons .icon-cloud-upload:before{content:'\e6cd'}
.chosen-icons .icon-bell-alt:before{content:'\e6d1'}
.chosen-icons .icon-coffee:before{content:'\e6d2'}
.chosen-icons .icon-file-text-o:before{content:'\e6d4'}
.chosen-icons .icon-file-text-alt:before{content:'\e6d4'}
.chosen-icons .icon-building:before{content:'\e6d5'}
.chosen-icons .icon-double-angle-left:before{content:'\e6dc'}
.chosen-icons .icon-double-angle-right:before{content:'\e6dd'}
.chosen-icons .icon-double-angle-up:before{content:'\e6de'}
.chosen-icons .icon-double-angle-down:before{content:'\e6df'}
.chosen-icons .icon-angle-left:before{content:'\e6e0'}
.chosen-icons .icon-angle-right:before{content:'\e6e1'}
.chosen-icons .icon-angle-up:before{content:'\e6e2'}
.chosen-icons .icon-angle-down:before{content:'\e6e3'}
.chosen-icons .icon-desktop:before{content:'\e6e4'}
.chosen-icons .icon-laptop:before{content:'\e6e5'}
.chosen-icons .icon-tablet:before{content:'\e6e6'}
.chosen-icons .icon-mobile:before{content:'\e6e7'}
.chosen-icons .icon-circle-blank:before{content:'\e6e8'}
.chosen-icons .icon-quote-left:before{content:'\e6e9'}
.chosen-icons .icon-quote-right:before{content:'\e6ea'}
.chosen-icons .icon-spinner:before{content:'\e6eb'}
.chosen-icons .icon-circle:before{content:'\e6ec'}
.chosen-icons .icon-reply:before{content:'\e6ed'}
.chosen-icons .icon-folder-close-alt:before{content:'\e6ef'}
.chosen-icons .icon-folder-open-alt:before{content:'\e6f0'}
.chosen-icons .icon-expand-alt:before{content:'\e6f1'}
.chosen-icons .icon-collapse-alt:before{content:'\e6f2'}
.chosen-icons .icon-smile:before{content:'\e6f3'}
.chosen-icons .icon-frown:before{content:'\e6f4'}
.chosen-icons .icon-meh:before{content:'\e6f5'}
.chosen-icons .icon-gamepad:before{content:'\e6f6'}
.chosen-icons .icon-keyboard:before{content:'\e6f7'}
.chosen-icons .icon-flag-alt:before{content:'\e6f8'}
.chosen-icons .icon-flag-checkered:before{content:'\e6f9'}
.chosen-icons .icon-terminal:before{content:'\e6fa'}
.chosen-icons .icon-code:before{content:'\e6fb'}
.chosen-icons .icon-reply-all:before{content:'\e6fc'}
.chosen-icons .icon-star-half-full:before{content:'\e6fd'}
.chosen-icons .icon-location-arrow:before{content:'\e6fe'}
.chosen-icons .icon-crop:before{content:'\e6ff'}
.chosen-icons .icon-code-fork:before{content:'\e700'}
.chosen-icons .icon-unlink:before{content:'\e701'}
.chosen-icons .icon-question:before{content:'\e702'}
.chosen-icons .icon-info:before{content:'\e703'}
.chosen-icons .icon-shield:before{content:'\e70b'}
.chosen-icons .icon-calendar-empty:before{content:'\e70c'}
.chosen-icons .icon-rocket:before{content:'\e70e'}
.chosen-icons .icon-chevron-sign-left:before{content:'\e70f'}
.chosen-icons .icon-chevron-sign-right:before{content:'\e710'}
.chosen-icons .icon-chevron-sign-up:before{content:'\e711'}
.chosen-icons .icon-chevron-sign-down:before{content:'\e712'}
.chosen-icons .icon-html5:before{content:'\e713'}
.chosen-icons .icon-anchor:before{content:'\e714'}
.chosen-icons .icon-unlock-alt:before{content:'\e715'}
.chosen-icons .icon-bullseye:before{content:'\e716'}
.chosen-icons .icon-ellipsis-h:before{content:'\e717'}
.chosen-icons .icon-ellipsis-v:before{content:'\e718'}
.chosen-icons .icon-rss-sign:before{content:'\e719'}
.chosen-icons .icon-play-sign:before{content:'\e71a'}
.chosen-icons .icon-minus-sign-alt:before{content:'\e71c'}
.chosen-icons .icon-plus-sign-alt:before{content:'\f0fe'}
.chosen-icons .icon-check-minus:before{content:'\e71d'}
.chosen-icons .icon-check-plus:before{content:'\f196'}
.chosen-icons .icon-level-up:before{content:'\e71e'}
.chosen-icons .icon-level-down:before{content:'\e71f'}
.chosen-icons .icon-check-sign:before{content:'\e720'}
.chosen-icons .icon-edit-sign:before{content:'\e721'}
.chosen-icons .icon-external-link-sign:before{content:'\e722'}
.chosen-icons .icon-share-sign:before{content:'\e723'}
.chosen-icons .icon-compass:before{content:'\e724'}
.chosen-icons .icon-collapse:before{content:'\e725'}
.chosen-icons .icon-collapse-top:before{content:'\e726'}
.chosen-icons .icon-expand:before{content:'\e727'}
.chosen-icons .icon-dollar:before{content:'\e728'}
.chosen-icons .icon-yen:before{content:'\e729'}
.chosen-icons .icon-file:before{content:'\e72b'}
.chosen-icons .icon-file-text:before{content:'\e72c'}
.chosen-icons .icon-sort-by-alphabet:before{content:'\e72d'}
.chosen-icons .icon-sort-by-alphabet-alt:before{content:'\e72e'}
.chosen-icons .icon-sort-by-attributes:before{content:'\e72f'}
.chosen-icons .icon-sort-by-attributes-alt:before{content:'\e730'}
.chosen-icons .icon-sort-by-order:before{content:'\e731'}
.chosen-icons .icon-sort-by-order-alt:before{content:'\e732'}
.chosen-icons .icon-thumbs-up:before{content:'\e733'}
.chosen-icons .icon-thumbs-down:before{content:'\e734'}
.chosen-icons .icon-long-arrow-down:before{content:'\e736'}
.chosen-icons .icon-long-arrow-up:before{content:'\e737'}
.chosen-icons .icon-long-arrow-left:before{content:'\e738'}
.chosen-icons .icon-long-arrow-right:before{content:'\e739'}
.chosen-icons .icon-apple:before{content:'\e73a'}
.chosen-icons .icon-windows:before{content:'\e73b'}
.chosen-icons .icon-android:before{content:'\e73c'}
.chosen-icons .icon-linux:before{content:'\e73d'}
.chosen-icons .icon-sun:before{content:'\e742'}
.chosen-icons .icon-moon:before{content:'\e743'}
.chosen-icons .icon-archive:before{content:'\e744'}
.chosen-icons .icon-bug:before{content:'\e745'}
.chosen-icons .icon-alipay:before,.chosen-icons .icon-zhifubao:before{content:'\e901'}
.chosen-icons .icon-alipay-square:before,.chosen-icons .icon-zhifubao-square:before{content:'\e900'}
.chosen-icons .icon-taobao:before{content:'\e902'}
.chosen-icons .icon-weibo:before{content:'\e746'}
.chosen-icons .icon-renren:before{content:'\e747'}
.chosen-icons .icon-chrome:before{content:'\e76c'}
.chosen-icons .icon-firefox:before{content:'\e76d'}
.chosen-icons .icon-ie:before{content:'\e76e'}
.chosen-icons .icon-opera:before{content:'\e76f'}
.chosen-icons .icon-safari:before{content:'\e770'}
.chosen-icons .icon-node:before{content:'\e76a'}
.chosen-icons .icon-layout:before{content:'\e768'}
.chosen-icons .icon-usecase:before{content:'\e74a'}
.chosen-icons .icon-stack:before{content:'\e769'}
.chosen-icons .icon-branch:before{content:'\e74b'}
.chosen-icons .icon-chat:before{content:'\e74c'}
.chosen-icons .icon-chat-line:before{content:'\e74f'}
.chosen-icons .icon-comment-line:before{content:'\e74f'}
.chosen-icons .icon-chat-dot:before{content:'\e750'}
.chosen-icons .icon-cube:before{content:'\e751'}
.chosen-icons .icon-database:before{content:'\f1c0'}
.chosen-icons .icon-align-left:before{content:'\e633'}
</style>
